version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: employee-db
    restart: always
    environment:
      POSTGRES_DB: employeedb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
